### PR TITLE
Added extended training statistics and exporting

### PR DESCRIPTION
**Pull request by HeDo88TH**
Added extended training statistics:

```
Statistics:
  Global accuracy: 61.233%
  Average accuracy: 42.140%
  Average sensitivity: 63.470%
  Average precision: 65.484%
  Average F1: 0.582

  Labels:

                     Label  |   Accuracy | Sensitivity |  Precision |         F1 |
  ------------------------- | ---------- |  ---------- | ---------- | ---------- |
                     ground |    38.798% |       0.400 |      0.930 |      0.559 |
             low_vegetation |    62.902% |       0.979 |      0.638 |      0.772 |
                   building |    38.148% |       0.816 |      0.417 |      0.552 |
          human_made_object |    28.712% |       0.344 |      0.635 |      0.446 |

```

The `--stats-file` switch allows the user to specify where to write the statistics:

```
{
    "avgAccuracy": 0.4213987197090668,
    "avgF1": 0.5824347254755816,
    "avgPrecision": 0.6548385499638956,
    "avgSensitivity": 0.6346952018424293,
    "globalAccuracy": 0.6123297944158843,
    "labels": {
        "building": {
            "accuracy": 0.3814783649011955,
            "f1": 0.5522755543529327,
            "precision": 0.41739624158896327,
            "sensitivity": 0.8159431070807461
        },
        "ground": {
            "accuracy": 0.38797587955720997,
            "f1": 0.5590527692469432,
            "precision": 0.9298705850867727,
            "sensitivity": 0.3996704554785759
        },
        "human_made_object": {
            "accuracy": 0.2871173171301706,
            "f1": 0.4461400888775913,
            "precision": 0.6345289742795166,
            "sensitivity": 0.34400616009240137
        },
        "low_vegetation": {
            "accuracy": 0.6290233172476911,
            "f1": 0.7722704894248593,
            "precision": 0.6375583989003297,
            "sensitivity": 0.9791610847179939
        }
    }
}
```

I am still working on this 👍 

Plus I added another switch `--eval-result` which points to a ply file where to write the validation result point cloud

### CODE REVIEW

**Comment by pierotofy** [comment]
Thanks, but before you go any further, can we **please** disable code linting? I can't review anything if you continue to change code formatting.

**Comment by HeDo88TH** [comment]
> Thanks, but before you go any further, can we **please** disable code linting? I can't review anything if you continue to change code formatting.
> 
> Also stop cleaning up stuff at random. If you want to cleanup the code, do so as part of a separate PR.

The cmake file had indentation inconsistencies: half of the file was 2 spaces, the other half was 4, and some parts had none at all.
I will deactivate the linter for the most perfluous things 👍

**Comment by pierotofy** [comment]
And revert the formatting changes.

**Comment by pierotofy** [comment]
Not quite; just look at this diff https://github.com/uav4geo/OpenPointClass/pull/16/files

**Comment by pierotofy** [comment]
I can't make changes:

```
 ! [remote rejected] HeDo88TH/main -> HeDo88TH/main (permission denied)
error: failed to push some refs to 'https://github.com/HeDo88TH/OpenPointClass'
```

**Comment by pierotofy** [comment]
Closing via #18

**Pull request closed without merging**
